arguments:
  init:
    - "-no-color"
  execute: 
    - "-auto-approve -no-color"
environment_variables:
  AWS_REGION: us-west-2
  CODE_URI: s3://argo-cloud-sync-brett-dev/terraform-example.tar.gz
  VAULT_ADDR: http://docker.for.mac.localhost:8200
framework: terraform
parameters:
  execute_container_image_uri: argocloudops/argo-cloudops-terraform:0.15.1
project_name: project1
target_name: target1
type: diff
workflow_template_name: argo-cloudops-single-step-vault-aws
